export const DEFAULT_FAVICON =
  "data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII=";
export const DEFAULT_FAVICON_TYPE = "image/x-icon";
export const DEFAULT_LANG = "en";
export const DEFAULT_CHARSET = "utf-8";
